Ninja: Cleaner Class Reference
Cleaner Class Reference
#include <clean.h>
Public Member Functions
int CleanAll ()
Clean all built files.
int cleaned_files_count () const
Cleaner (State *state, const BuildConfig &config, DiskInterface *disk_interface)
Build a cleaner object with the given disk_interface (Useful for testing).
Cleaner (State *state, const BuildConfig &config)
Build a cleaner object with a real disk interface.
int CleanRule (const char *rule)
Clean the file produced by the given rule.
int CleanRule (const Rule *rule)
Clean all the file built with the given rule rule.
int CleanRules (int rule_count, char *rules[])
Clean the file produced by the given rules.
int CleanTarget (const char *target)
Clean the given target target.
int CleanTarget (Node *target)
Clean the given target and all the file built for it.
int CleanTargets (int target_count, char *targets[])
Clean the given target targets.
bool IsVerbose () const
Private Member Functions
void DoCleanRule (const Rule *rule)
void DoCleanTarget (Node *target)
Helper recursive method for CleanTarget().
bool FileExists (const string &path)
bool IsAlreadyRemoved (const string &path)
void PrintFooter ()
void PrintHeader ()
void Remove (const string &path)
Remove the given path file only if it has not been already removed.
int RemoveFile (const string &path)
Remove the file path.
void Report (const string &path)
void Reset ()
Private Attributes
int cleaned_files_count_
BuildConfig config_
DiskInterface * disk_interface_
set< string > removed_
State * state_
int status_
Detailed Description
Definition at line 30 of file clean.h.
Constructor & Destructor Documentation
Cleaner::Cleaner (State * state, const BuildConfig & config)
Build a cleaner object with a real disk interface.
Definition at line 28 of file clean.cc.
Cleaner::Cleaner (State * state, const BuildConfig & config, DiskInterface * disk_interface)
Build a cleaner object with the given disk_interface (Useful for testing).
Definition at line 38 of file clean.cc.
Member Function Documentation
int Cleaner::CleanAll ()
Clean all built files.
Returns:
non-zero if an error occurs.
Definition at line 101 of file clean.cc.
References State::edges_, PrintFooter(), PrintHeader(), Remove(), Reset(), state_, and status_.
Referenced by TEST_F().
int Cleaner::cleaned_files_count () const [inline]
Returns:
the number of file cleaned.
Definition at line 67 of file clean.h.
References cleaned_files_count_.
Referenced by TEST_F().
int Cleaner::CleanRule (const char * rule)
Clean the file produced by the given rule.
Returns:
non-zero if an error occurs.
Definition at line 192 of file clean.cc.
References CleanRule(), Error(), State::LookupRule(), Reset(), state_, and status_.
int Cleaner::CleanRule (const Rule * rule)
Clean all the file built with the given rule rule.
Returns:
non-zero if an error occurs.
Definition at line 182 of file clean.cc.
References DoCleanRule(), PrintFooter(), PrintHeader(), Reset(), and status_.
Referenced by CleanRule(), and TEST_F().
int Cleaner::CleanRules (int rule_count, char * rules[])
Clean the file produced by the given rules.
Returns:
non-zero if an error occurs.
Definition at line 206 of file clean.cc.
References DoCleanRule(), Error(), IsVerbose(), State::LookupRule(), PrintFooter(), PrintHeader(), Reset(), state_, and status_.
int Cleaner::CleanTarget (const char * target)
Clean the given target target.
Returns:
non-zero if an error occurs.
Definition at line 136 of file clean.cc.
References CleanTarget(), Error(), State::LookupNode(), Reset(), state_, and status_.
int Cleaner::CleanTarget (Node * target)
Clean the given target and all the file built for it.
Returns:
non-zero if an error occurs.
Definition at line 126 of file clean.cc.
References DoCleanTarget(), PrintFooter(), PrintHeader(), Reset(), and status_.
Referenced by CleanTarget(), and TEST_F().
int Cleaner::CleanTargets (int target_count, char * targets[])
Clean the given target targets.
Returns:
non-zero if an error occurs.
Definition at line 150 of file clean.cc.
References DoCleanTarget(), Error(), IsVerbose(), State::LookupNode(), PrintFooter(), PrintHeader(), Reset(), state_, and status_.
void Cleaner::DoCleanRule (const Rule * rule) [private]
Definition at line 169 of file clean.cc.
References State::edges_, Rule::name_, Remove(), and state_.
Referenced by CleanRule(), and CleanRules().
void Cleaner::DoCleanTarget (Node * target) [private]
Helper recursive method for CleanTarget().
Definition at line 115 of file clean.cc.
References Node::file_, Node::in_edge_, Edge::inputs_, FileStat::path_, and Remove().
Referenced by CleanTarget(), and CleanTargets().
bool Cleaner::FileExists (const string & path) [private]
Returns:
whether the file path exists.
Definition at line 54 of file clean.cc.
References disk_interface_, and DiskInterface::Stat().
Referenced by Remove().
bool Cleaner::IsAlreadyRemoved (const string & path) [private]
Returns:
whether the given path has already been removed.
Definition at line 80 of file clean.cc.
References removed_.
Referenced by Remove().
bool Cleaner::IsVerbose () const [inline]
Returns:
whether the cleaner is in verbose mode.
Definition at line 72 of file clean.h.
References config_, BuildConfig::dry_run, BuildConfig::QUIET, BuildConfig::VERBOSE, and BuildConfig::verbosity.
Referenced by CleanRules(), CleanTargets(), PrintHeader(), and Report().
void Cleaner::PrintFooter () [private]
Definition at line 95 of file clean.cc.
References cleaned_files_count_, config_, BuildConfig::QUIET, and BuildConfig::verbosity.
Referenced by CleanAll(), CleanRule(), CleanRules(), CleanTarget(), and CleanTargets().
void Cleaner::PrintHeader () [private]
Definition at line 85 of file clean.cc.
References config_, IsVerbose(), BuildConfig::QUIET, and BuildConfig::verbosity.
Referenced by CleanAll(), CleanRule(), CleanRules(), CleanTarget(), and CleanTargets().
void Cleaner::Remove (const string & path) [private]
Remove the given path file only if it has not been already removed.
Definition at line 64 of file clean.cc.
References config_, BuildConfig::dry_run, FileExists(), IsAlreadyRemoved(), removed_, RemoveFile(), Report(), and status_.
Referenced by CleanAll(), DoCleanRule(), and DoCleanTarget().
int Cleaner::RemoveFile (const string & path) [private]
Remove the file path.
Returns:
whether the file has been removed.
Definition at line 50 of file clean.cc.
References disk_interface_, and DiskInterface::RemoveFile().
Referenced by Remove().
void Cleaner::Report (const string & path) [private]
Definition at line 58 of file clean.cc.
References cleaned_files_count_, and IsVerbose().
Referenced by Remove().
void Cleaner::Reset () [private]
Definition at line 227 of file clean.cc.
References cleaned_files_count_, removed_, and status_.
Referenced by CleanAll(), CleanRule(), CleanRules(), CleanTarget(), and CleanTargets().
Member Data Documentation
int Cleaner::cleaned_files_count_ [private]
Definition at line 99 of file clean.h.
Referenced by cleaned_files_count(), PrintFooter(), Report(), and Reset().
BuildConfig Cleaner::config_ [private]
Definition at line 97 of file clean.h.
Referenced by IsVerbose(), PrintFooter(), PrintHeader(), and Remove().
DiskInterface* Cleaner::disk_interface_ [private]
Definition at line 100 of file clean.h.
Referenced by FileExists(), and RemoveFile().
set<string> Cleaner::removed_ [private]
Definition at line 98 of file clean.h.
Referenced by IsAlreadyRemoved(), Remove(), and Reset().
State* Cleaner::state_ [private]
Definition at line 96 of file clean.h.
Referenced by CleanAll(), CleanRule(), CleanRules(), CleanTarget(), CleanTargets(), and DoCleanRule().
int Cleaner::status_ [private]
Definition at line 101 of file clean.h.
Referenced by CleanAll(), CleanRule(), CleanRules(), CleanTarget(), CleanTargets(), Remove(), and Reset().
The documentation for this class was generated from the following files:
clean.h
clean.cc