Ninja: ninja.cc File Reference
ninja.cc File Reference
#include "ninja.h"
#include <errno.h>
#include <getopt.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
#include <sys/types.h>
#include "browse.h"
#include "build.h"
#include "build_log.h"
#include "graph.h"
#include "graphviz.h"
#include "parsers.h"
#include "util.h"
#include "clean.h"
Classes
struct RealFileReader
An implementation of ManifestParser::FileReader that actually reads the file.
Functions
int CmdBrowse (State *state, int argc, char *argv[])
int CmdClean (State *state, int argc, char *argv[], const BuildConfig &config)
int CmdGraph (State *state, int argc, char *argv[])
int CmdQuery (State *state, int argc, char *argv[])
int CmdRules (State *state, int argc, char *argv[])
int CmdTargets (State *state, int argc, char *argv[])
int CmdTargetsList (State *state)
int CmdTargetsList (State *state, const string &rule_name)
int CmdTargetsList (const vector< Node * > &nodes, int depth)
int CmdTargetsList (const vector< Node * > &nodes, int depth, int indent)
int CmdTargetsSourceList (State *state)
int GuessParallelism ()
int main (int argc, char **argv)
void usage (const BuildConfig &config)
Variables
option options []
Function Documentation
int CmdBrowse (State * state, int argc, char * argv[])
Definition at line 170 of file ninja.cc.
References Error(), and RunBrowsePython().
Referenced by main().
int CmdClean (State * state, int argc, char * argv[], const BuildConfig & config)
Definition at line 297 of file ninja.cc.
References Cleaner::CleanAll(), Cleaner::CleanRules(), Cleaner::CleanTargets(), and Error().
Referenced by main().
int CmdGraph (State * state, int argc, char * argv[])
Definition at line 107 of file ninja.cc.
References GraphViz::AddTarget(), Error(), GraphViz::Finish(), State::LookupNode(), State::RootNodes(), and GraphViz::Start().
Referenced by main().
int CmdQuery (State * state, int argc, char * argv[])
Definition at line 138 of file ninja.cc.
References Error(), State::GetNode(), Node::in_edge_, Edge::inputs_, Rule::name_, Node::out_edges_, and Edge::rule_.
Referenced by main().
int CmdRules (State * state, int argc, char * argv[])
Definition at line 283 of file ninja.cc.
References State::rules_.
Referenced by main().
int CmdTargets (State * state, int argc, char * argv[])
Definition at line 250 of file ninja.cc.
References CmdTargetsList(), CmdTargetsSourceList(), Error(), and State::RootNodes().
Referenced by main().
int CmdTargetsList (State * state)
Definition at line 237 of file ninja.cc.
References State::edges_.
int CmdTargetsList (State * state, const string & rule_name)
Definition at line 218 of file ninja.cc.
References State::edges_.
int CmdTargetsList (const vector< Node * > & nodes, int depth)
Definition at line 202 of file ninja.cc.
References CmdTargetsList().
int CmdTargetsList (const vector< Node * > & nodes, int depth, int indent)
Definition at line 184 of file ninja.cc.
Referenced by CmdTargets(), and CmdTargetsList().
int CmdTargetsSourceList (State * state)
Definition at line 206 of file ninja.cc.
References State::edges_.
Referenced by CmdTargets().
int GuessParallelism ()
Definition at line 69 of file ninja.cc.
Referenced by main().
int main (int argc, char ** argv)
Definition at line 329 of file ninja.cc.
References Builder::AddTarget(), State::bindings_, Builder::Build(), State::build_log_, CanonicalizePath(), CmdBrowse(), CmdClean(), CmdGraph(), CmdQuery(), CmdRules(), CmdTargets(), BuildConfig::dry_run, Error(), Fatal(), getopt_long(), GuessParallelism(), BuildLog::Load(), ManifestParser::Load(), BindingEnv::LookupVariable(), BuildLog::OpenForWrite(), optarg, optind, BuildConfig::parallelism, BuildLog::SetConfig(), usage(), BuildConfig::VERBOSE, and BuildConfig::verbosity.
void usage (const BuildConfig & config)
Definition at line 48 of file ninja.cc.
References BuildConfig::parallelism.
Referenced by main().
Variable Documentation
option options[]
Initial value:
 {
  { "help", no_argument, NULL, 'h' },
  { }
}
Definition at line 43 of file ninja.cc.