Ninja: StatTest Struct Reference
StatTest Struct Reference
Public Member Functions
Node * GetNode (const string &path)
virtual bool MakeDir (const string &path)
Create a directory, returning false on failure.
bool MakeDirs (const string &path)
Create all the parent directories for path; like mkdir -p `basename path`.
virtual string ReadFile (const string &path, string *err)
Read a file to a string. Fill in |err| on error.
virtual int Stat (const string &path)
stat() a file, returning the mtime, or 0 if missing and -1 on other errors.
Public Attributes
map< string, time_t > mtimes_
State state_
vector< string > stats_
Detailed Description
Definition at line 105 of file ninja_test.cc.
Member Function Documentation
Node * StateTestWithBuiltinRules::GetNode (const string & path) [inherited]
Definition at line 25 of file test.cc.
References State::GetNode(), and StateTestWithBuiltinRules::state_.
Referenced by BuildTest::Dirty().
virtual bool StatTest::MakeDir (const string & path) [inline, virtual]
Create a directory, returning false on failure.
Implements DiskInterface.
Definition at line 109 of file ninja_test.cc.
bool DiskInterface::MakeDirs (const string & path) [inherited]
Create all the parent directories for path; like mkdir -p `basename path`.
Definition at line 75 of file ninja_jumble.cc.
References DirName(), DiskInterface::MakeDir(), and DiskInterface::Stat().
Referenced by Builder::StartEdge().
virtual string StatTest::ReadFile (const string & path, string * err) [inline, virtual]
Read a file to a string. Fill in |err| on error.
Implements DiskInterface.
Definition at line 113 of file ninja_test.cc.
int StatTest::Stat (const string & path) [virtual]
stat() a file, returning the mtime, or 0 if missing and -1 on other errors.
Implements DiskInterface.
Definition at line 122 of file ninja_test.cc.
References mtimes_, and stats_.
Member Data Documentation
map<string, time_t> StatTest::mtimes_
Definition at line 118 of file ninja_test.cc.
Referenced by Stat().
State StateTestWithBuiltinRules::state_ [inherited]
Definition at line 32 of file test.h.
Referenced by BuildTest::BuildTest(), StateTestWithBuiltinRules::GetNode(), and StateTestWithBuiltinRules::StateTestWithBuiltinRules().
vector<string> StatTest::stats_
Definition at line 119 of file ninja_test.cc.
Referenced by Stat().
The documentation for this struct was generated from the following file:
ninja_test.cc