Ninja: EvalString Struct Reference
EvalString Struct Reference
A tokenized string that contains variable references.
#include <eval_env.h>
Public Types
typedef vector< pair< string,
TokenType > > TokenList
enum TokenType { RAW, SPECIAL }
Public Member Functions
const bool empty () const
string Evaluate (Env *env) const
bool Parse (const string &input, string *err, size_t *err_index=NULL)
const string & unparsed () const
Public Attributes
TokenList parsed_
string unparsed_
Detailed Description
A tokenized string that contains variable references.
Can be evaluated relative to an Env.
Definition at line 43 of file eval_env.h.
Member Typedef Documentation
typedef vector<pair<string, TokenType> > EvalString::TokenList
Definition at line 52 of file eval_env.h.
Member Enumeration Documentation
enum EvalString::TokenType
Enumerator:
RAW
SPECIAL
Definition at line 51 of file eval_env.h.
Member Function Documentation
const bool EvalString::empty () const [inline]
Definition at line 48 of file eval_env.h.
References unparsed_.
Referenced by ManifestParser::ParseEdge(), and Edge::RecomputeDirty().
string EvalString::Evaluate (Env * env) const
Definition at line 82 of file eval_env.cc.
References Env::LookupVariable(), parsed_, and RAW.
Referenced by Edge::EvaluateCommand(), Edge::GetDescription(), Edge::LoadDepFile(), ManifestParser::ParseEdge(), ManifestParser::ParseLet(), and TEST().
bool EvalString::Parse (const string & input, string * err, size_t * err_index = NULL)
Definition at line 30 of file eval_env.cc.
References parsed_, RAW, SPECIAL, and unparsed_.
Referenced by Rule::ParseCommand(), ManifestParser::ParseEdge(), ManifestParser::ParseLet(), ManifestParser::ParseRule(), and TEST().
const string& EvalString::unparsed () const [inline]
Definition at line 47 of file eval_env.h.
References unparsed_.
Referenced by ManifestParser::ParseRule(), and TEST().
Member Data Documentation
TokenList EvalString::parsed_
Definition at line 53 of file eval_env.h.
Referenced by Evaluate(), and Parse().
string EvalString::unparsed_
Definition at line 50 of file eval_env.h.
Referenced by empty(), Parse(), and unparsed().
The documentation for this struct was generated from the following files:
eval_env.h
eval_env.cc