Ninja: SubprocessSet Struct Reference
SubprocessSet Struct Reference
SubprocessSet runs a poll() loop around a set of Subprocesses.
#include <subprocess.h>
Public Member Functions
void Add (Subprocess *subprocess)
void DoWork ()
Subprocess * NextFinished ()
Public Attributes
queue< Subprocess * > finished_
vector< Subprocess * > running_
Detailed Description
SubprocessSet runs a poll() loop around a set of Subprocesses.
DoWork() waits for any state change in subprocesses; finished_ is a queue of subprocesses as they finish.
Definition at line 52 of file subprocess.h.
Member Function Documentation
void SubprocessSet::Add (Subprocess * subprocess)
Definition at line 127 of file subprocess.cc.
References running_.
Referenced by RealCommandRunner::StartCommand(), and TEST().
void SubprocessSet::DoWork ()
Definition at line 131 of file subprocess.cc.
References Subprocess::done(), finished_, Subprocess::OnFDReady(), and running_.
Referenced by TEST(), and RealCommandRunner::WaitForCommands().
Subprocess * SubprocessSet::NextFinished ()
Definition at line 179 of file subprocess.cc.
References finished_.
Referenced by RealCommandRunner::NextFinishedCommand().
Member Data Documentation
queue<Subprocess*> SubprocessSet::finished_
Definition at line 58 of file subprocess.h.
Referenced by DoWork(), NextFinished(), TEST(), and RealCommandRunner::WaitForCommands().
vector<Subprocess*> SubprocessSet::running_
Definition at line 57 of file subprocess.h.
Referenced by Add(), RealCommandRunner::CanRunMore(), DoWork(), TEST(), and RealCommandRunner::WaitForCommands().
The documentation for this struct was generated from the following files:
subprocess.h
subprocess.cc