Ninja: State Struct Reference
State Struct Reference
Global state (file status, loaded rules) for a single run.
#include <ninja.h>
Public Member Functions
Edge * AddEdge (const Rule *rule)
void AddIn (Edge *edge, const string &path)
void AddOut (Edge *edge, const string &path)
void AddRule (const Rule *rule)
Node * GetNode (const string &path)
Node * LookupNode (const string &path)
const Rule * LookupRule (const string &rule_name)
vector< Node * > RootNodes (string *error)
StatCache * stat_cache ()
State ()
Public Attributes
BindingEnv bindings_
struct BuildLog * build_log_
vector< Edge * > edges_
All the edges of the graph.
map< string, const Rule * > rules_
All the rules used in the graph.
StatCache stat_cache_
Static Public Attributes
static const Rule kPhonyRule
Detailed Description
Global state (file status, loaded rules) for a single run.
Definition at line 84 of file ninja.h.
Constructor & Destructor Documentation
State::State ()
Definition at line 124 of file ninja_jumble.cc.
References AddRule(), and kPhonyRule.
Member Function Documentation
Edge * State::AddEdge (const Rule * rule)
Definition at line 140 of file ninja_jumble.cc.
References bindings_, edges_, Edge::env_, and Edge::rule_.
Referenced by Edge::LoadDepFile(), ManifestParser::ParseEdge(), and TEST().
void State::AddIn (Edge * edge, const string & path)
Definition at line 162 of file ninja_jumble.cc.
References GetNode(), Edge::inputs_, and Node::out_edges_.
Referenced by ManifestParser::ParseEdge(), and TEST().
void State::AddOut (Edge * edge, const string & path)
Definition at line 168 of file ninja_jumble.cc.
References GetNode(), Node::in_edge_, Edge::outputs_, and Warning().
Referenced by ManifestParser::ParseEdge(), and TEST().
void State::AddRule (const Rule * rule)
Definition at line 135 of file ninja_jumble.cc.
References LookupRule(), Rule::name_, and rules_.
Referenced by ManifestParser::ParseRule(), State(), and TEST().
Node * State::GetNode (const string & path)
Definition at line 155 of file ninja_jumble.cc.
References StatCache::GetFile(), FileStat::node_, and stat_cache_.
Referenced by AddIn(), AddOut(), StateTestWithBuiltinRules::GetNode(), Edge::LoadDepFile(), and TEST().
Node * State::LookupNode (const string & path)
Definition at line 148 of file ninja_jumble.cc.
References StatCache::GetFile(), FileStat::node_, and stat_cache_.
Referenced by Builder::AddTarget(), Cleaner::CleanTarget(), and Cleaner::CleanTargets().
const Rule * State::LookupRule (const string & rule_name)
Definition at line 128 of file ninja_jumble.cc.
References rules_.
Referenced by AddRule(), Cleaner::CleanRule(), Cleaner::CleanRules(), ManifestParser::ParseEdge(), and ManifestParser::ParseRule().
vector< Node * > State::RootNodes (string * error)
Returns:
the root node(s) of the graph. (Root nodes have no output edges).
Parameters:
error where to write the error message if somethings went wrong.
Definition at line 178 of file ninja_jumble.cc.
References edges_.
StatCache* State::stat_cache () [inline]
Definition at line 87 of file ninja.h.
References stat_cache_.
Member Data Documentation
BindingEnv State::bindings_
Definition at line 105 of file ninja.h.
Referenced by AddEdge(), main(), and ManifestParser::ManifestParser().
struct BuildLog* State::build_log_
Definition at line 106 of file ninja.h.
Referenced by Builder::Builder(), main(), and Edge::RecomputeDirty().
vector<Edge*> State::edges_
All the edges of the graph.
Definition at line 104 of file ninja.h.
Referenced by AddEdge(), Cleaner::CleanAll(), Cleaner::DoCleanRule(), and RootNodes().
const Rule State::kPhonyRule [static]
Definition at line 108 of file ninja.h.
Referenced by Edge::is_phony(), Edge::LoadDepFile(), and State().
map<string, const Rule*> State::rules_
All the rules used in the graph.
Definition at line 102 of file ninja.h.
Referenced by AddRule(), and LookupRule().
StatCache State::stat_cache_
Definition at line 100 of file ninja.h.
Referenced by GetNode(), LookupNode(), and stat_cache().
The documentation for this struct was generated from the following files:
ninja.h
ninja_jumble.cc