Ninja: RealDiskInterface Struct Reference
RealDiskInterface Struct Reference
Implementation of DiskInterface that actually hits the disk.
#include <ninja.h>
Public Member Functions
virtual bool MakeDir (const string &path)
Create a directory, returning false on failure.
bool MakeDirs (const string &path)
Create all the parent directories for path; like mkdir -p `basename path`.
virtual string ReadFile (const string &path, string *err)
Read a file to a string. Fill in |err| on error.
virtual int RemoveFile (const string &path)
Remove the file named path.
virtual int Stat (const string &path)
stat() a file, returning the mtime, or 0 if missing and -1 on other errors.
virtual ~RealDiskInterface ()
Detailed Description
Implementation of DiskInterface that actually hits the disk.
Definition at line 63 of file ninja.h.
Constructor & Destructor Documentation
virtual RealDiskInterface::~RealDiskInterface () [inline, virtual]
Definition at line 64 of file ninja.h.
Member Function Documentation
bool RealDiskInterface::MakeDir (const string & path) [virtual]
Create a directory, returning false on failure.
Implements DiskInterface.
Definition at line 80 of file ninja_jumble.cc.
References Error().
bool DiskInterface::MakeDirs (const string & path) [inherited]
Create all the parent directories for path; like mkdir -p `basename path`.
Definition at line 53 of file ninja_jumble.cc.
References DirName(), DiskInterface::MakeDir(), and DiskInterface::Stat().
Referenced by Builder::StartEdge().
string RealDiskInterface::ReadFile (const string & path, string * err) [virtual]
Read a file to a string. Fill in |err| on error.
Implements DiskInterface.
Definition at line 70 of file ninja_jumble.cc.
int RealDiskInterface::RemoveFile (const string & path) [virtual]
Remove the file named path.
It behaves like 'rm -f path' so no errors are reported if it does not exists.
Returns:
0 if the file has been removed, 1 if the file does not exist, and -1 if an error occurs.
Implements DiskInterface.
Definition at line 88 of file ninja_jumble.cc.
References Error().
int RealDiskInterface::Stat (const string & path) [virtual]
stat() a file, returning the mtime, or 0 if missing and -1 on other errors.
Implements DiskInterface.
Definition at line 29 of file ninja_jumble.cc.
References Error().
The documentation for this struct was generated from the following files:
ninja.h
ninja_jumble.cc