Ninja: subprocess_test.cc File Reference
subprocess_test.cc File Reference
#include "subprocess.h"
#include "test.h"
Functions
TEST_F (SubprocessTest, SetWithMulti)
TEST_F (SubprocessTest, SetWithSingle)
TEST_F (SubprocessTest, BadCommandStderr)
TEST_F (SubprocessTest, GoodCommandStdout)
Function Documentation
TEST_F (SubprocessTest , SetWithMulti)
Definition at line 75 of file subprocess_test.cc.
TEST_F (SubprocessTest , SetWithSingle)
Definition at line 61 of file subprocess_test.cc.
References Subprocess::Done(), Subprocess::Finish(), Subprocess::GetOutput(), and Subprocess::Start().
TEST_F (SubprocessTest , BadCommandStderr)
Definition at line 48 of file subprocess_test.cc.
References Subprocess::Done(), Subprocess::Finish(), Subprocess::GetOutput(), Subprocess::OnPipeReady(), and Subprocess::Start().
TEST_F (SubprocessTest , GoodCommandStdout)
Definition at line 34 of file subprocess_test.cc.
References Subprocess::Done(), Subprocess::Finish(), Subprocess::GetOutput(), Subprocess::OnPipeReady(), and Subprocess::Start().