Ninja: util.cc File Reference
util.cc File Reference
#include "util.h"
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <vector>
Functions
bool CanonicalizePath (string *path, string *err)
Canonicalize a path like "foo/../bar.h" into just "bar.h".
void Error (const char *msg,...)
Log an error message.
void Fatal (const char *msg,...)
Log a fatal message and exit.
Function Documentation
bool CanonicalizePath (string * path, string * err)
Canonicalize a path like "foo/../bar.h" into just "bar.h".
Definition at line 43 of file util.cc.
Referenced by Edge::LoadDepFile(), main(), ManifestParser::ParseEdge(), and TEST().
void Error (const char * msg, ...)
Log an error message.
Definition at line 34 of file util.cc.
Referenced by State::AddOut(), Cleaner::CleanRules(), Cleaner::CleanTargets(), CmdBrowse(), CmdClean(), CmdGraph(), CmdQuery(), CmdTargets(), Cleaner::FileExists(), main(), RealDiskInterface::MakeDir(), Cleaner::RemoveFile(), and RealDiskInterface::Stat().
void Fatal (const char * msg, ...)
Log a fatal message and exit.
Definition at line 24 of file util.cc.
Referenced by Subprocess::Finish(), main(), Subprocess::OnFDReady(), and Subprocess::Start().